### ISSUE TITLE
Examples for tests.

### ISSUE THREAD

**Issue by venikman** [kryz81/deno-api-example#1]
@kryz81 Thank you very much for a great example. I am as TDD fan always look at new technology how I can write tests for it. Can you point me to some examples with tests or can I try to came with tests here?

**Comment by kryz81** [comment]
@venikman 

There are two libraries to write tests:
- Deno standard library: https://deno.land/std/testing/README.md
- a 3rd-party (Jest like):  https://deno.land/x/expect/README.md

**Here is a simple example:**
```typescript
import { test } from "https://deno.land/std/testing/mod.ts";
import {
  assertEquals,
  assertMatch
} from "https://deno.land/std/testing/asserts.ts";

import createId from "./createId.ts";

test({
  name: "it returns a ID in uuid v4 format",
  fn: () => {
    // when
    const id = createId();

    // then
    assertEquals(id.length, 36);
    assertMatch(id, /^[a-f0-9\-]+$/);
  }
});
```

Currently I don't know how to test code with dependencies (imports mocking). Maybe you could find a way to do it?
